url: https://kls2177.github.io
baseurl:
gems: ['jekyll/scholar']

# Site settings
title: Karen Smith
email: ksmith@ldeo.columbia.edu
description: "Climate and Atmospheric Science"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 00CCFF
  secondary-dark: 333

# pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:ksmith@ldeo.columbia.edu
 # - title: twitter
 #   url: http://twitter.com/rabernat
  - title: github
    url: http://github.com/kls2177

# Postal address (add as many lines as necessary)
address:
  - line: Department of Physical and Environmental Sciences
  - line: University of Toronto Scarborough

# Build settings
markdown: kramdown
permalink: pretty

# Bibliography settings
scholar:
  style: american-meteorological-society
  locale: en

  sort_by: year
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
