community:
  - Faculty Member, Seminars on Science, American Museum of Natural History,
      New York, NY, USA, 2012 - 2016
  - Session Convener, AGU Fall Meeting, San Francisco, CA, 2012, 2014.
  - Member, American Geophysical Union
  - Member, American Meteorological Society
  - Reviewer for Science, Nature Climate Change
  - Reviewer for Nature Communications
  - Reviewer for Journal of Climate
  - Reviewer for Journal of the Atmospheric Sciences
  - Reviewer for Journal of Geophysical Research Atmospheres
  - Reviewer for Journal of Environmental Research Atmospheres
  - Reviewer for Geophysical Research Letters
  - Reviewer for Climate Dynamics
  - Reviewer for National Science Foundation
  - Reviewer for Marsden Foundation (New Zealand)
  - Reviewer for New Zealand Antarctic Research Institute

university:
  -
